[package]
name = "whatlang-rb"
version = "0.1.9"
authors = ["Kitaiti Makoto <KitaitiMakoto@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
magnus = "0.8"
whatlang = "0.18.0"

[lib]
crate-type = ["cdylib"]
