[package]
name = "whatlang"
version = "0.2.0"
authors = ["Kitaiti Makoto <KitaitiMakoto@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
lazy_static = "1.5.1"
rutie = "0.14.0"
whatlang-rs = { package = "whatlang", version = "0.18.0", registry = "crates-io" }

[lib]
crate-type = ["cdylib"]
